#@TYPE: Machine
#@NAME: KickPi K7
#@DESCRIPTION: KickPi K7 based on Rockchip RK3576

require conf/machine/include/rk3576.inc

KERNEL_DEVICETREE = "rockchip/rk3576-kickpi-k7.dtb"
UBOOT_MACHINE = "rk3576_defconfig"
RK_UBOOT_SPL = "1"

MACHINE_FEATURES:append = " wifi bluetooth pci screen touchscreen"
