# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "kickpi"
BBFILE_PATTERN_kickpi = "^${LAYERDIR}/"
BBFILE_PRIORITY_kickpi = "6"

LAYERDEPENDS_kickpi = "core rockchip"
LAYERSERIES_COMPAT_kickpi = "scarthgap"
